#This is an example file to run compose
services:
  web:
    image: ghcr.io/jnunez2301/jellyfin-wireless-remote:latest
    environment:
      # If default host is provided on the main page it will fill the form automatically
      # e.g: VITE_JELLYFIN_DEFAULT_HOST=yourjellyfindomain.com
      - "${VITE_JELLYFIN_DEFAULT_HOST}"
      # You can set a default user and password from Jellyfin to avoid login every time
      # [!] If your server is exposed to the internet it's not recommended to use this option for security reasons since VITE exposes this to the public
      - "${VITE_JELLYFIN_DEFAULT_USERNAME}"
      - "${VITE_JELLYFIN_DEFAULT_PASSWORD}"
    ports:
      - "${SERVER_PORT:-8080}:3000"
    container_name: jellyfin_wireless_remote
    restart: unless-stopped
